[features]
seeds = false
skip-lint = false
[programs.devnet]
vault = "AvyqWo2UHmAnn6KLqL5SVZk7UyeVco1Bgim6PosNVvvH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/rustam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
